### ISSUE TITLE
Option to custmize the text?

### ISSUE THREAD

**Issue by ganlanyuan** [gotomedia/Sketch-PageNumbers#3]
Thanks for this very useful plugin!
Could you add an option to edit the text?
e.g. simply 1, 2, 3 without the "PAGE".
Or 1 of 2

**Comment by pkiula** [comment]
Same here. How to do this? Without this simple feature, it's not very useful.

**Comment by UXrichard** [comment]
This plugin is temperamental at best. Sometimes it works, sometimes not. Especially when making changes to the document after having added the page numbers once, for example if I add or remove canvases and try to run the plugin again, it sometimes gets the page numbers in the wrong sequence, or starts from 51 instead of 1. This is a huge waste of time and would be easier to just manually add page numbers.

**Comment by beccayukelson** [comment]
I often use sketch with one artboard per per page. Is it possible for there to be a way to count the pages rather than the artboards within a page? Right now if I start a new page with this plugin, the page count starts from one again. Thank you!

**Comment by beccayukelson** [comment]
Yes, how do we get rid of the word "page" in this plug in?
